[package]
name = "rusty-genius-brain-teaser"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-genius = { path = "../genius" }
rusty-genius-core = { path = "../core" }
rusty-genius-brain-cortex = { path = "../cortex" }
anyhow = "1.0"
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"

[features]
real-engine = ["rusty-genius-brain-cortex/real-engine"]
