[package]
name = "rusty-genius"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-genius-core = { path = "../core" }
facecrab = { path = "../facecrab" }
rusty-genius-brain-stem = { path = "../brainstem" }
rusty-genius-brain-cortex = { path = "../cortex" }
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"

[features]
default = []
metal = ["rusty-genius-brain-cortex/metal", "real-engine"]
cuda = ["rusty-genius-brain-cortex/cuda", "real-engine"]
vulkan = ["rusty-genius-brain-cortex/vulkan", "real-engine"]
real-engine = ["rusty-genius-brain-cortex/real-engine"]
