[package]
name = "rusty-genius"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Public facade and API key for rusty-genius"
publish.workspace = true

[dependencies]
rusty-genius-core = { path = "../core", version = "0.1.0" }
facecrab = { path = "../facecrab", version = "0.1.0" }
rusty-genius-stem = { path = "../brainstem", version = "0.1.0" }
rusty-genius-cortex = { path = "../cortex", version = "0.1.0" }
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"

[features]
default = []
metal = ["rusty-genius-cortex/metal", "real-engine"]
cuda = ["rusty-genius-cortex/cuda", "real-engine"]
vulkan = ["rusty-genius-cortex/vulkan", "real-engine"]
real-engine = ["rusty-genius-cortex/real-engine"]
