[package]
name = "rusty-genius"
version = "0.0.1"
edition = "2021"
publish = true

[dependencies]
rusty-genius-core = { path = "../core", version = "0.0.1" }
facecrab = { path = "../facecrab", version = "0.0.1" }
rusty-genius-stem = { path = "../brainstem", version = "0.0.1" }
rusty-genius-cortex = { path = "../cortex", version = "0.0.1" }
async-std = { version = "1.12", features = ["attributes"] }
futures = "0.3"

[features]
default = []
metal = ["rusty-genius-cortex/metal", "real-engine"]
cuda = ["rusty-genius-cortex/cuda", "real-engine"]
vulkan = ["rusty-genius-cortex/vulkan", "real-engine"]
real-engine = ["rusty-genius-cortex/real-engine"]
