[package]
name = "rusty-genius"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-genius-core = { path = "../core" }
facecrab = { package = "rusty-genius-facecrab", path = "../facecrab" }
rusty-genius-brain-stem = { path = "../brainstem" }
rusty-genius-brain-cortex = { path = "../cortex" }

[features]
default = []
metal = ["rusty-genius-brain-cortex/metal"]
cuda = ["rusty-genius-brain-cortex/cuda"]
real-engine = ["rusty-genius-brain-cortex/real-engine"]
