[package]
name = "rusty-genius-brain-stem"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-genius-core = { path = "../core" }
facecrab = { package = "rusty-genius-facecrab", path = "../facecrab" }
rusty-genius-brain-cortex = { path = "../cortex" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
