name: Release-plz release workflow

on:
  push:
    branches:
      - main

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: rusty-genius-publish
    if: ${{ github.repository_owner == 'tmzt' }} # REQUIRED FOR SECURITY
    permissions:
      contents: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Close old PRs
        run: |
          gh pr list --state open --json number,title | jq '.[].number' | xargs -I {} gh pr close {} -c "Auto-closed by release-plz"
      - name: Run release-plz
        # Pinning to a specific commit to avoid breaking changes from the action itself.
        uses: release-plz/action@63ab0c2746bedc448370bad4b0b3d536458398b0 # v0.5.50
        with:
          command: release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # # Create a PR with the new versions and changelog, preparing the next release.
  # release-plz-pr:
  #   name: Release-plz PR
  #   runs-on: ubuntu-latest
  #   if: ${{ github.repository_owner == 'tmzt' }} # REQUIRED FOR SECURITY
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   concurrency:
  #     group: release-plz-${{ github.ref }}
  #     cancel-in-progress: false
  #   steps:
  #     - *checkout
  #     - *install-rust
  #     - name: Run release-plz
  #       # Pinning to a specific commit to avoid breaking changes from the action itself.
  #       uses: release-plz/action@63ab0c2746bedc448370bad4b0b3d536458398b0 # v0.5.50
  #       with:
  #         command: release-pr
  #         dry_run: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
